mackerelio/go-check-plugins

check-file-age/README.md, check-file-age/check_file_age.go
Hi,
This plugin checks file stat to monitor invalid file state.
For example, the file names `target` is monitored `mtime`.
* half day is over then `warning`
* 1 day is over then `critical`
```
$ check-file-age -f target -c 86400 -w 43200
```
inspired by https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/check_file_age.pl
=> Add check-file-age

check-mysql-connection/README.md, check-mysql-connection/check-mysql-connection.go, check-mysql-replication/README.md, check-mysql-replication/check-mysql-replication.go
I'd like to add two plugins to official.
* check-mysql-connection
- Checks the number of connections.
* check-mysql-replication
- Checks the replication status and its Second Behind Master.
These plugins are from my repository.
https://github.com/hiroakis/mackerel-agent-checks-plugins
* mackerel-check-mysql-connection
* mackerel-check-mysql-replication
These plugins have been working on our production environment for several months.
If these are useful for people, please add.
=> Mysql checks

check-log/check-log.go
strconv.Atoi return of the int32.
Changing to return to int64.
Error Message
```
/usr/local/bin/check-log --file=logfile --pattern='paten'
LOG UNKNOWN: strconv.ParseInt: parsing "2203473635": value out of range
```
=> bug check-log return int64

check-file-age/check_file_age.go
If mtime showed in message, I can have more piece of mind when watching host pages.
before
```
~ $ /usr/local/bin/check-file-age -f /var/log/test.log -w 240 -c 600
FileAge OK: /var/log/test.log is 0 seconds old and 62025259 bytes.
```
after
```
~ $ ./check-file-age -f /var/log/test.log -w 240 -c 600
FileAge OK: /var/log/test.log is 0 seconds old (13:52:16) and 62015637 bytes.
```
=> check-file-age: show time in message

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- add check-postgresql #47
- [check-ntpoffset] work on ntp 4.2.2 #50
- check-file-age: show time in message #51
- add --no-check-certificate options to check_http #52
- add check-mailq, currently only available for postfix. #54
- add check-mailq and check-postgresql into package #55
=> Release version 0.3.0

check-ntpoffset/check-ntpoffset.go
When `check-ntpoffset -h` run, it duplicates help messages and returns a status of 2.
Error in parsing flags is not a critical of ntpd.
before:
```console
$ /usr/local/bin/check-ntpoffset -h
Usage:
check-ntpoffset [OPTIONS]
Application Options:
-c, --critical= critical if the ntpoffset is over (default: 100)
-w, --warning=  warning if the ntpoffset is over (default: 50)
Help Options:
-h, --help      Show this help message
NTP CRITICAL: Usage:
check-ntpoffset [OPTIONS]
Application Options:
-c, --critical= critical if the ntpoffset is over (default: 100)
-w, --warning=  warning if the ntpoffset is over (default: 50)
Help Options:
-h, --help      Show this help message
```
after:
```console
$ ./check-ntpoffset -h
Usage:
check-ntpoffset [OPTIONS]
Application Options:
-c, --critical= critical …
```
=> Fix duplicated help message

check-procs/check_procs.go, check-procs/check_procs_unix.go
I add new option for checking PPID.
It checks PPID of target processes like the following:
```console
$ ./check-procs --ppid 1 -p bash -W 0 -C 0
Procs OK: Found 0 matching processes; cmd /bash/; ppid 1
```
=> check-procs: check PPID

check-tcp/README.md, check-tcp/check-tcp.go
I want to use this.
It's able to check localhost's ssl daemon. e.g.
```
check-tcp  -S -H 127.0.0.1 -p 443 -s 'GET / HTTP/1.0\r\n\r\n' -e 'nginx' --no-check-certificate -E 
```
=> [tcp] Add --no-check-certificate

check-tcp/check-tcp_test.go
The IPv6 test for check-tcp fails on my OS X machine for some reason. This patch fixes it, at least on my environment.
I don't know why the original code doesn't run on my OS X environment but I see no reason using Hijacker: http.HandleFunc handles everything fine.
=> Fix check-tcp IPv6 testcase on OSX(?)

check-redis/check-redis.go
To avoid `panic: runtime error: invalid memory address or nil pointer dereference`
This is happeded when the defer tried closing nil redis.Client.
I tested both master binary and pr-branch binary.
```
/m/d/g/g/check-redis ❯❯❯ ps aux | grep redis-server
great           45931   0.0  0.0  2461800    468 s004  S+   水06PM   1:16.09 redis-server 127.0.0.1:6380
great            5145   0.0  0.0  3060960    644 s040  S+   19 216    2:42.71 redis-server *:6379
great           17361   0.0  0.0  2434820    684 s055  S+   11:53AM   0:00.00 grep --color redis-server
```
```
/m/d/g/g/check-redis ❯❯❯ ./check-redis reachable --host=localhost --port=6379
Redis Reachable OK: version: 3.0.6
/m/d/g/g/check-redis ❯❯❯ ./check-redis reachable --host=localhost --port=6380
Redis Reachable OK: version: 3.0.6 …
```
=> check-redis: Fixed panic

check-redis/check-redis.go
The `check-redis slave` command reports OK even if the master link is down, in which case we would like to be notified about the disconnected link.
This patch makes the command to report Critical if the link is down.
=> check-redis: Report critical if master_link_status is down

check-procs/check_procs.go
`check-procs -p xxx` invoked by mackerel-agent output `Found 1 matching processes` when no xxx process exists .
mackerel-agent invokes a check command using `/bin/sh -c ""`, which for example creates a process tree like below.
```
great@ip-10-0-1-176:~$ /bin/sh -c "ps axfwwo user,ppid,pid,vsz,rss,pcpu,nlwp,state,etime,time,command"
USER      PPID   PID    VSZ   RSS %CPU NLWP S     ELAPSED     TIME COMMAND
great    30523 30524  22392  3884  0.0    1 S       01:48 00:00:00          \_ -bash
great    30524 30615   4440   652  0.0    1 S       00:00 00:00:00              \_ /bin/sh -c ps axfwwo user,ppid,pid,vsz,rss,pcpu,nlwp,state,etime,time,command
great    30615 30616  18276  1428  0.0    1 R       00:00 00:00:00                  \_ ps axfwwo …
```
=> check-procs: Fixed the counting logic with -p

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- add check-solr #46
-  add check-jmx-jolokia #68
- check-memcached #69
- Add scheme option to check-elasticsearch #70
- Check file size #72
- Add uptime sub command to check-mysql #73
- add check-cert-file #74
- [tcp] Add --no-check-certificate #75
- Fixed slurp. conn.read returns content with EOF #76
- Fix check-tcp IPv6 testcase on OSX(?) #77
- check-redis: Report critical if master_link_status is down #79
- check-redis: Fixed panic #80
- check-procs: Fixed the counting logic with -p #81
- add check-uptime #82
- add file-size, jmx-jolokia, memcached, solr, uptime into package config #84
=> Release version 0.5.0

packaging/rpm/mackerel-check-plugins.spec
If rpm includes dir, following conflict error occurs
```
Transaction check error:
file /usr/bin from install of mackerel-check-plugins-0.5.2-1.x86_64 conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
file /usr/bin from install of mackerel-agent-plugins-0.19.2-1.x86_64 conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
```
=> fix: rpm should not include dir

check-uptime/README.md, check-uptime/check-uptime.go
relate with https://github.com/mackerelio/go-check-plugins/pull/87#issuecomment-197206911
@Songmu intend to use `--warning-under` `--warning-over`, but implementation is not.
This is the pull request to amend that implementation.
=> Use `--warning-*` instead of `--warn-*` 

check-masterha/README.md, check-masterha/check_masterha.go, check-masterha/check_masterha_repl.go, check-masterha/check_masterha_repl_test.go, check-masterha/check_masterha_ssh.go, check-masterha/check_masterha_ssh_test.go, check-masterha/check_masterha_status.go, check-masterha/check_masterha_status_test.go, check-masterha/check_masterha_test.go, check-masterha/mock/masterha.go
Monitor MasterHA status.
```
$ check-masterha --conf /path/to/masterha
```
```
[plugin.checks.masterha-status]
command = "/path/to/check-masterha status --all"
[plugin.checks.masterha-repl]
command = "/path/to/check-masterha repl --conf /path/to/masterha_cluster.cnf"
[plugin.checks.masterha-ssh]
command = "/path/to/check-masterha ssh --conf /path/to/masterha_cluster.cnf"
```
* [Master HA Manager](https://code.google.com/p/mysql-master-ha/)
=> added check-masterha command to check masterha status

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- no panic check-masterha when not found the targets, and refactoring #108
- Use config.json to list up packaging target plugins #109
- Keep binaries on old path hard corded #110
=> Release version 0.6.1

check-load/check_load.go
This error is always occurred (but, not printed):
`boolean flag `-r/percpu' may not have default values, they always default to `false' and can only be turned on`
=> Fixed argument parser error:

check-mysql/replication.go
Look at the below image. When MySQL slave try to connect to the master but failed, IO thread status will be "Connecting". In this case, `check-mysql replication` cannot detect replication stop.  This pull request fixes it.
=> fix check-mysql replication to detect IO thread 'Connecting'

check-file-age/check_file_age.go
I got a message with a extra newline.
A newline is specified although it has been already added in `ckr.Exit()`
Like this:
```console
$ ./check-file-age -w 200 -f ./check-file-age
FileAge WARNING: ./check-file-age is 544 seconds old (10:50:04) and 2629472 bytes.
$
```
=> [file-age] Remove unnecessary newline

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- fix check-mysql replication to detect IO thread 'Connecting' #116
- [file-age] Remove unnecessary newline #117
=> Release version 0.6.3

check-log/check-log.go, check-log/check_log_test.go
`check-log` exit `UNKNOWN` if logfile which specified by `LogFile` does not exist.
This pull request is add `skip-not-exist` option for skip searching logfile content if logfile does not exist.
=> Add option for skip searching logfile content if logfile does not exist

check-log/check-log.go, check-log/check_log_test.go
Name of state file is frequently conflict in current implement. So I change the strategy.
=> [check-log] [incompatible] Chagne state file naming strategy and location

check-procs/check_procs_unix.go
This pull request fixes the `-s` option of check-procs.
ref: this small bug seems to be introduced in #64
=> Fix state in check-procs

check-ntservice/check_ntservice.go
ErrorControl mean how the errors is noticed to users. Not to check the status of process.
=> remove checking Ignore

check-windows-eventlog/check-windows-eventlog.go
It's difficult to specify those values in -type option since toml format
have problem to write value contain spaces.
=> fix matching for 'Audit Success' and 'Audit Failure'

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- fix matching for 'Audit Success' and 'Audit Failure' #139
=> Release version 0.9.3

check-log/check-log.go
Temporary file may not locate at same disk-partition, or same filesytem.
When the path of temporary file doesn't locate at same disk-partition,
os.Rename works like copying file.
=> Write the file in same directory

check-log/lib/check-log.go
When lower-case filename is specified with `-file`, check-log try to make directory `%APPDATA%\temp\check-log\C:`. (`:` is invalid)
=> check lower-case driver letters

check-log/lib/check-log.go, check-log/lib/check-log_test.go
Current specification of `check-log` , it is difficult to satisfy `AND` as the log monitoring condition.
This p-r is to make it possible to perform log monitoring that satisfies all the patterns when multiple `--pattern` are specified.
=> [check-log]  When specified multiple pattern, perform search that satisfies all conditions

.travis.yml
CI Failure: https://travis-ci.org/mackerelio/go-check-plugins/builds/255560624#L1105-L1109
ref: https://github.com/mackerelio/mackerel-agent/pull/396
=> Make `make deb` work in Travis

.gitignore
Same here as https://github.com/mackerelio/mackerel-agent-plugins/pull/379. Related: #186.
=> [nit] add plugin executables pattern in .gitignore

check-disk/lib/check-disk.go
- `-p` / `-N`
- fixed output inflation when a value specified twice (ex. -N ext4 -N ext4)
- `-x`
- now accpets twice
- `-X`
- fixed exclusion failure when specified twice
=> fix check-disk options: -x, -X, -p, -N

check-tcp/lib/check-tcp_test.go
TestHTTPIPv6 in check-tcp tests start failing recently: https://travis-ci.org/mackerelio/go-check-plugins/builds
From the error message, maybe ipv6 networking does not work in Travis container. (Even if so, I don't know why it has been working...)
So I'd like to skip this test for now.
=> Skip IPv6 tests in Travis

check-http/lib/check_http.go, check-http/lib/check_http_test.go
[go-magi][], yet another external monitoring tool, currently execute check-http command using os/exec package.
Generally speaking, we must pay some costs while calling fork or exec syscalls, and also have to abandon cross-platform features while touching `ProcessState`, even writing in Go.
[go-magi]: https://github.com/aereal/go-magi
=> [check-http] Expose checkhttp.Run due for using check-http as a library

check-tcp/README.md, check-tcp/lib/check-tcp.go, check-tcp/lib/check-tcp_test.go
I Added -W option in order to suppress CRITICAL when error occurred.
-W sets the exit status at error occurrence to WARNING.
In the case of request succeeded, evaluation result of -c option eval takes priority.
=> [check-tcp] add -W option

check-log/lib/check-log.go, check-log/lib/check-log_test.go
- If the file size is zero, the following error will be ignored.
=> [check-log]improve skip bytes when file size is zero

check-cert-file/lib/check-cert-file.go, check-procs/lib/check_procs.go
This pull request fixes the problem `check-procs --help` and `check-cert-file --help` outputs the command usage twice.
```sh
% for f in check-*; do (cd $f >/dev/null && test $(go run main.go --help 2>&1 | grep 'Application Options' | wc -l) -gt 1 && echo $f); done
check-cert-file/
check-procs/
```
=> Fix duplicated output of usage with --help argument

check-windows-eventlog/README.md
The following EVENTTYPE can not be detected as an alert.
- Success
- Audit Success
- Information
I think that it is better to mention this in the README.
=> [check-windows-eventlog] fix README - Some of the listed EVENTTYPEs can not be detected as alerts

check-log/lib/check-log.go, check-log/lib/check-log_test.go
Added pattern display suppression option because it is hard to see when the target pattern becomes longer.
Assuming use with `--return` option.
=> [check-log] Add option to suppress pattern display

check-ntpoffset/lib/check-ntpoffset.go
In our usecase, compare localtime to ntp server is better (just like nagios plugins).
I think compare localtime to ntp server is more direct(and have some benefit) way than check via time-sync daemon.
=> Add feature use ntp server

check-http/lib/check_http.go, check-http/lib/check_http_test.go
net/http uses `req.Host` for Host header, not `req.Headers`.
`req.Host` is set to `req.URL.Host` by default, so `Host` in `req.Headers` is ignored.
In this commit, set `req.Host` from parsed header if specified.
> For client requests, certain headers such as Content-Length
> and Connection are automatically written when needed and
> values in Header may be ignored. See the documentation
> for the Request.Write method.
>
> https://golang.org/pkg/net/http/#Request
=> [check-http] Set Host header via req.Host

check-smtp/README.md, check-smtp/lib/check-smtp.go, check-smtp/lib/check-smtp_test.go, check-smtp/main.go
This plugin can be used check behave for smtp server.
Plugin sends following commands in basis of SMTP Protocol.
- `HELO/EHLO`
- `STARTTLS` (optional)
- `AUTH` (optional, only `PLAIN` supported)
- `MAIL`
- `RSET`
- `QUIT`
=> Add check-smtp

check-http/lib/check_http.go, check-http/lib/check_http_test.go
`check-http` cannot check redirects currently since [`http.Client` follow redirects by default](https://golang.org/src/net/http/client.go#L728). 
In this PR, I added `--max-redirects` option (like `--max-redirs` in curl or `--max-redirect` in wget) by setting `client.checkRedirect`.
```console
$ ./mackerel-check http --help
Usage:
mackerel-check [OPTIONS]
Application Options:
-u, --url=                  A URL to connect to
-s, --status=               mapping of HTTP status
--no-check-certificate  Do not check certificate
-i, --source-ip=            source IP address
-H=                         HTTP request headers
-p, --pattern=              Expected pattern in the content
--max-redirects=        Maximum number of redirects followed (default: 10)
Help Options:
-h, --help …
```
=> [check-http] Add --max-redirects option

check-elasticsearch/lib/check_elasticsearch.go, check-http/lib/check_http.go, check-jmx-jolokia/lib/check_jmx_jolokia.go, check-solr/lib/ping.go
Currently check plugins request to target HTTP endpoints with `net/http`'s default user-agent "Go-http-client/1.1".
In `check-http`, users can override it by the HTTP header option, but others cannot event override.
With this p-r:
- in `check-http`, fill default user-agent if `opts.Header` doesn't specify one
- in other check plugins which does HTTP request, set user-agent
All (default) user-agents are simply their plugin names like `check-http`.
=> add User-Agent header to http check plugins

check-redis/lib/check-redis.go
add replication subcommand insteam of slave
because it seems that the behavior that slave command returns OK if role is master is not intuitive in the PR(https://github.com/mackerelio/go-check-plugins/pull/259).
```
[y_uuki@redis01 ~]$ redis-cli info | grep role
role:master
[y_uuki@redis01 ~]$ ./check-redis replication
Redis Replication UNKNOWN: couldn't get master_link_status
[y_uuki@redis01 ~]$ ./check-redis replication --skip-master
Redis Replication OK: role is master
```
```
[y_uuki@redis002 ~]$ redis-cli info | grep role
role:slave
[y_uuki@redis002 ~]$ ./check-redis replication
Redis Replication OK: master_link_status: up
```
=> [check-redis] add replication subcommand

check-http/README.md, check-http/lib/check_http.go, check-http/lib/check_http_test.go
Same as `curl`'s --connect-to option, which is added in 7.49.0.
```shell
check-http --connect-to=example.com:443:127.0.0.1:8080 https://example.com
check-http --connect-to=:443:127.0.0.1:8080 https://example.com
check-http --connect-to=example.com::127.0.0.1:8080 https://example.com
check-http --connect-to=example.com::127.0.0.1: https://example.com
check-http --connect-to=:443::8080 https://127.0.0.1
```
"My app host serves https://mackerel.io/, and I'd like to check it's https response".
- In HTTP, `check-http -H Host: mackerel.io http://127.0.0.1/` works
- If I'm not interested in certs, `check-http --no-check-certificate -H Host: mackerel.io https://127.0.0.1` works
- but I'm interested not only HTTP response but also HTTPS certificate!
I cared ipv6's address roughly, but not tested …
=> [check-http] Support --connect-to option

check-disk/lib/check-disk.go
On Windows, there are no "inodes" and checks on them should be skipped.
However, the current version always raises wranings / errors if `-w N%` / `-c N%` is specified.
This PR fixes it by skipping checks if total inodes is zero (`gopsutil/disk` returns `InodesTotal = 0` on Windows https://github.com/shirou/gopsutil/blob/master/disk/disk_windows.go).
The change may affect other (non-Windows) environments, but I think it is OK because talking about the "percentage" of 0/0 is nonsense...
=> [check-disk] skip checks if there are no inodes

check-disk/lib/check-disk.go
As mentioned [here](https://github.com/mackerelio/go-check-plugins/pull/265#discussion_r241683338), checking inodes% when `-w N%` / `-c N%` specified is not preferable behavior, as the help does not refer to it.
This PR fixes it so that one can use `-w` / `-c` for disk% and `-W` / `-K` for inodes% separately.
=> [check-disk] Do not check inodes% along with disk%

check-log/lib/check-log.go, check-log/lib/check-log_test.go, check-log/lib/check-log_unix.go, check-log/lib/check-log_unix_test.go
I added signal handler to check-log plugin to catch timeout from mackerel-agent.
When *check-log* plugin catches SIGTERM (Unix) or `os.Interrupt` (Windows), the plugin will read bytes until next newline and stop reading logs, and respond result to Mackerel.
=> [check-log]stop reading logs on SIGTERM

check-log/lib/check-log.go, check-log/lib/check-log_test.go, check-windows-eventlog/lib/check-windows-eventlog.go
This pull request introduces https://github.com/natefinch/atomic library. The library is simple enough and fixes the problem os.Rename is not atomic on Windows. Also reduces one remove call compared to our writeFileAtomically function.
=>  [check-log][check-windows-eventlog] Improve atomic write

check-http/README.md, check-http/lib/check_http.go, check-http/lib/check_http_test.go
Although check-http can request using proxy via `HTTP_PROXY` environment variable, imo it's useful when we can specify the proxy url from command line option.
=> [check-http] add --proxy option

check-ntpoffset/README.md, check-ntpoffset/lib/check-ntpoffset.go, check-ntpoffset/lib/check-ntpoffset_test.go
From #276.
In addition to the original PR, I made some changes:
- refactor and fix parse functions
- add a command-line flag `--check-stratum`
- add test cases
=> Add NTP stratum check to check-ntpoffset

check-procs/lib/check_procs.go, check-procs/lib/check_procs_test.go
The Current specification of check-procs, makes it difficult to check multiple processes in one definition.
Setting many definitions has the problem of consuming a large amount of resources instantaneously.
This p-r is to make it possible to perform process monitoring in each pattern when multiple `--pattern` options are specified one definition.
```
$ check-procs -p "sshd" -p "bash"
Procs OK:
Found 5 matching processes; cmd /sshd/
Found 2 matching processes; cmd /bash/
```
=> [check-procs] If more than one pattern is specified, find processes that meet any of the conditions.

check-http/lib/check_http.go
Just a small improvement so you can check a website which requires basic auth. (i called it "--user" because that's how this parameter is called in curl)
=> add --user to check-http

check-log/lib/check-log.go, check-log/lib/check-log_state_test.go, check-log/lib/testdata/invalid_json.json, check-log/lib/testdata/unexpected_json.json
I'm not sure this is the best approach, but worth consider…
=> [check-log] Ignore broken/unexpected json on reading state

check-log/lib/check-log.go
This pull request improves performance of check-log when a lot of error messages written.
It reduces using `+` operator for strings.
=> [check-log] Make building the error lines efficiently

check-log/lib/check-log.go, check-log/lib/check-log_test.go
This p-r is for excludes the lines that contain exclude strings in the `AND` condition when multiple `--exclude` options are specified.
=> [check-log] When specified multiple exclude pattern, perform search that excludes all conditions.

check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_test.go, go.mod, go.sum
Currently we use only simple `errors.New`, therefore use Go's standard "errors" seems enough.
=> [check-aws-cloudwatch-logs] Use "errors" instead of "github.com/pkg/errors"

check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_test.go
Fixes #327
go-flags package unquote options by default. This behavior was introduced at:
https://github.com/jessevdk/go-flags/pull/96
In the case of #327, `-p "\"err:\""` will be unquoted, then the same as `-p err:`. So I think `err:` expression might be going to violate the [Filter syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html).
**Notes**
I fixed only for *check-aws-cloudwatch-logs* plugin. Other plugins is not fixed yet.
=> disable unquoting of go-flags

check-aws-cloudwatch-logs/README.md, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_test.go
When using check-aws-cloudwatch-logs, the following error could occur:
`CloudWatch Logs UNKNOWN: ThrottlingException: Rate exceeded status code: 400, request id: xxxxxxxxxx`
As a result of investigation, it was caused by `Throttling` of` cloudwatchlogs.FilterLogEvents` function used in check-aws-cloudwatch-logs.
In order to avoid this error as much as possible, it is now possible to set the number of retries for aws-sdk-go API call.
=> [check-aws-cloudwatch-logs] Added option to specify AWS API retry count

check-ssl-cert/lib/check-ssl-cert.go
The intermediate- and root-certificates received from the server will be checked.
To check the raw certificates sent from the server:
```console
% openssl s_client -servername <domain> -connect  <domain>:443 -showcerts </dev/null >c.pem
% openssl crl2pkcs7 -nocrl -certfile c.pem | openssl pkcs7 -print_certs -text -noout
```
=> [check-ssl-cert] check intermediate- and root-certificates

check-load/lib/check_load.go
Hi,
When using check-load `--percpu` option, the cpu load output is not divided per cpu. That could bring some misunderstood when define threshold warning/critical.
=> fix check-load percpu output

.travis.yml, Makefile, packaging/deb-v2/debian/control, packaging/rpm/mackerel-check-plugins-v2.spec, packaging/rpm/mackerel-check-plugins.spec
I added recipes to make the packages for arm64 architecture.
see mackerelio/mkr#310
=> add arm64 architecture packages

check-postgresql/README.md, check-postgresql/lib/check-postgresql.go
This PR adds the [`sslrootcert` option](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLROOTCERT) to `check-postgresql` in order to specify the root certificate for SSL certificate verification. This should be used with `sslverify=verify-ca` or `verify-full`.
I don't give a short name since `sslrootcert` is not the popular use case compared to other options for now. 
cf. https://www.postgresql.org/docs/current/ssl-tcp.html 
```sh
$ mkdir -p certs
$ pushd certs
$ openssl req -new -nodes -text -out root.csr \
-keyout root.key -subj "/CN=root.example.local"
$ chmod og-rwx root.key
$ openssl x509 -req -in root.csr -text -days 365 -sha256 \
-extensions v3_ca -signkey root.key \
-out root.crt
$ openssl req -new -nodes -text -out server.csr \
-keyout server.key -subj …
```
=> [check-postgresql] Add sslrootcert option

check-load/lib/check_load.go
Moving the "if opts.PerCPU" into its own for loop makes the code cleaner in my opinion. There are 2 loops now but is is only a loop of 3.
It is important to go through all the loops to get the load divided by cpu (if that option selected). However, on the flip side it is important to not loop through all of the loops when you have reached a critical threshold.
This has to due to how the critical and warn are like this "-w 1,1,1 -c 2,2,2" and the actual value could be 2, 1.5, 1.  
In this scenario the 1st minute average is critical but if we keep looping 5 and 15 minute average would put it back to a Warning and we don't want that.  
We could have added an additional if critical (previous loop) before moving on to warning but it gets messy. 
I also pulled the runtime.NumCPU() outside of …
=> Closes #455 check-load fix null pointer issue when critical

check-disk/lib/check-disk.go, check-disk/lib/check-disk_test.go, go.mod, go.sum
Changes in gopsutil@v3 are listed here: https://github.com/shirou/gopsutil/blob/master/_tools/v3migration/v3Changes.md
- Fixes build failure on macOS https://github.com/shirou/gopsutil/issues/958
- Also fixes treatment for fstype=none
=> [check-disk] upgrade gopsutil to v3 and fix treatment for fstype=none

Makefile, check-disk/test.sh, check-ldap/test.sh, check-postgresql/test.sh, check-redis/test.sh, test.bash
I changed workflow to run tests (**&lt;plugin&gt;/test.sh**) for each plugins.
The "make lint cover testconvention test" task ends up with the reports of each tests of the plugin.
```
OK: check-disk/test.sh
OK: check-ldap/test.sh
OK: check-postgresql/test.sh
OK: check-redis/test.sh
```
see also mackerelio/mackerel-agent-plugins#771
=> [ci] run tests on the workflow

.github/workflows/create-release-pr.yml, tool/update-docs.pl
We are using [Mackerel::ReleaseUtils](https://metacpan.org/pod/Mackerel::ReleaseUtils) in the version update process and want to replace it.
In this pull request, I'm writing the code to try the replacement.
This GitHub Action does not actually work, but runs in "dry-run" mode.
=> Replacing the version update process

check-mysql/README.md, check-mysql/lib/check-mysql.go, check-mysql/test-tls.sh, test.bash
I added three options for use encrypted connection to the server.
* `--tls` Enables TLS connection
* `--tls-root-cert [ca.pem]` The root certificate used for TLS certificate verification
* `--tls-skip-verify` Disable TLS certificate verification
=> [check-mysql] add --tls, --tls-root-cert and --tls-skip-verify options

check-mysql/lib/replication.go
http://jmoiron.github.io/sqlx/#query
> The connection used by the Query remains active until either all rows are exhausted by the iteration via `Next`, or `rows.Close()` is called, at which point it is released. For more information, see the section on the connection pool.
=> check-mysql: Closes `checkReplication` rows

check-redis/lib/check-redis.go, go.mod, go.sum
The redis client library `fzzy/radix` seems to be removed, so I migrated the library to `gomodule/redigo`.
=> [check-redis] migrate redis client library to redigo

check-log/README.md, check-log/lib/check-log.go, check-log/lib/check-log_test.go
Directory delimiters and regular expressions can conflict in windows.
Therefore, add a directory option to facilitate file-pattern settings.
=> [check-log] add search-in-directory option

.github/workflows/test.yml
I did upgrade Go toolchain.
Next Go version will be scheduled Mar 2022.
https://go.dev/blog/go1.18beta2
=> upgrade Go: 1.16 -> 1.17

check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_test.go
Now check-aws-cloudwatch-logs plugin uses `FilterLogEvents` API and implements pagination by itself. But I think it's better to use `FilterLogEventsPages` API.
=> [check-aws-cloudwatch-logs] use FilterLogEventsPages API

check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_test.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_unix.go
similar to #268
I fixed to handle timeout signal from mackerel-agent in `check-aws-cloudwatch-logs` plugin to stop the plugin gracefully.
Now, when received timeout signal, `check-aws-cloudwatch-logs` skip checking log events fetched until then and these log events will never be checked.
So, I fixed the plugin to check log events before stopping when received timeout signal.
=> [check-aws-cloudwatch-logs] stop gracefully on timeout signal

check-disk/README.md, check-disk/lib/check-disk.go, check-disk/test.sh
=> Ignores fuse.portal partitions

check-mysql/test-tls.sh, check-mysql/test.sh, check-mysql/test_57/docker-compose.yml, check-mysql/test_57/test.sh, check-mysql/test_8/docker-compose.yml, check-mysql/test_8/test.sh, check-mysql/wait.sh, test.bash
- Specify docker platform explicitly so that they can be run on Docker Desktop for Mac on Apple silicon
- Run all tests on CI
- Because of this, it takes about 1 minute longer than before (but I think it's acceptable)
- Fix some unstable tests
- Refactor test scripts
=> Improve tests for check-mysql

check-uptime/lib/check-uptime.go, check-uptime/lib/check-uptime_test.go
Before rewrite `check-uptime.go`, can't test correctly because of reference.
Here is an example.
`check-uptime-test.go`
```go
func TestCheckUptime(t *testing.T) {
tests := []struct {
args []string
want checkers.Status
}{
{
[]string{},
checkers.OK,
},
{
[]string{"-w", "-1"},
checkers.OK,
},
{
[]string{"-W", "-1"},
checkers.WARNING,
},
{
[]string{"-c", "-1"},
checkers.OK,
},
{
[]string{"-C", "-1"},
checkers.CRITICAL,
},
}
for _, tt := range tests {
ckr := run(tt.args)
assert.Equal(t, tt.want, ckr.Status)
}
}
```
debug `fmt.print(opts)` in `run` function
```zsh
~/Desktop/go-check-plugins/check-uptime/lib
$ go test -v
=== RUN   TestCheckUptime
{<nil> <nil> <nil> <nil> <nil> <nil>}
{<nil> 0xc0000a6aa8 <nil> <nil> <nil> <nil>}
{<nil> 0xc0000a6aa8 <nil> <nil> 0xc0000a6b30 <nil>}
{<nil> …
```
=> [uptime] rewite to testable and add test

Makefile, packaging/deb-v2/debian/rules, packaging/deb/debian/rules
Changed to use xz format for compressing debian packages. refer https://github.com/mackerelio/mackerel-agent-plugins/pull/981
The environment ubuntu-latest for GitHub Actions is ubuntu 22.04.
It turns out that glibc is new and the built binary compatibility is broken in some environments.
So I made a change to build with CGO_ENABLED=0
=> added compile option, fix packaging format

check-log/lib/check-log_test.go, check-log/lib/check-log_unix_test.go, check-tcp/lib/check-tcp_test.go, check-windows-eventlog/lib/check_windows_eventlog_test.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
=> test: use `T.TempDir` to create temporary test directory

.github/dependabot.yml, .github/workflows/create-release-pr.yml
This repository's workflows look antiquated. Deprecated features and runtimes of Github Actions will soon be unavailable.
So we activate dependabot for GitHub Actions to automate updates.
=> Enables Dependabot version updates for GitHub Actions

check-ntservice/README.md, check-ntservice/lib/check_ntservice.go, check-ntservice/lib/check_ntservice_test.go
The following problems with check-ntservice have been corrected
- Since the service name determination is a partial match, the intended service may not be checked, so an `--exact` option to check with a full matched by `--service-name` has been added.
- Since all services were checked, the last checked result was returned. This has been corrected to return the result of the first check.
- When a nonexistent service is specified, it is now set to UNKNOWN.
- Improved the message to include the service name even if the result is OK.
- Fixed command description.
When this fix is merged, existing users may be affected as follows.
- A result that was OK without matching service may become UNKNOWN. This is a correct condition.
- If multiple services are matched, the result of the first service …
=> Improve ntservice

check-tcp/README.md, check-tcp/lib/check-tcp.go, check-tcp/lib/check-tcp_test.go
TCP connection monitoring is provided by a mechanism that assumes the port is open.
In some cases, it is possible that the state in which the port is closed is correct, and in such cases, the following shell workaround can be used.
```toml
[plugin.checks.dummy]
command = "check-tcp -H <host> -p <port> && exit 2 || exit 0"
```
However, since it is more convenient to be provided as an option, we have added a --expect-closed flag to determine that the state in which the port is closed is normal.
When this option is enabled, it will only work for processes that make connections.
=> [check-tcp] Supports option to monitor that ports are closed.

check-ntservice/README.md
I found a mistype option in README.md of check-ntservice.
`-E` should be `-x`. (I checked the code and its behavior)
=> check-ntservice: exclude should be -x, not -E

check-log/lib/check-log.go
=> fix the line handling of UTF-16le

Makefile
We build the binary for rpm/deb package on `ubuntu-latest` GitHub Actions runner image.
The generated binary may depend on a libc that is too new for the environment we support.
So, build with `CGO_ENABLED=0` flag.
=> CGO_ENABLED=0 when build for packaging

check-log/lib/check-log.go
I created the patch https://github.com/mackerelio/go-check-plugins/pull/823 , but this patch has a bug.
Procedure for reproducing : 
- Apply this patch.
```diff
diff --git a/check-log/lib/check-log.go b/check-log/lib/check-log.go
index f942c58..2efa68e 100644
--- a/check-log/lib/check-log.go
+++ b/check-log/lib/check-log.go
@@ -16,6 +16,7 @@ import (
"regexp"
"strconv"
"strings"
+       "time"
"github.com/jessevdk/go-flags"
"github.com/mackerelio/checkers"
@@ -566,6 +567,8 @@ var errFileNotFoundByInode = fmt.Errorf("old file not found")
func findFileByInode(inode uint, dir string) (string, error) {
entries, readDirErr := os.ReadDir(dir)
+       fmt.Println("sleeping")
+       time.Sleep(10 * time.Second)
for _, entry := range entries {
fi, err := entry.Info()
if err != nil && …
```
=> Fix: check-log panic with invalid memory address or nil pointer dereference

check-redis/lib/check-redis.go, check-redis/test.sh
I believe `check-redis reachable` is intented to check a rechability.
Unlike the expectation of returning OK / CRITICAL, this command returns OK / UNKNOWN.
Here is a proposal patch to change the behavior. This may be breaking change, but it should meet user's expectation.
=> return CRITICAL instead of UNKNOWN when check-redis reachable is failed

check-ntservice/lib/check_ntservice.go
This PR aims to enable the `--status-as` option in check-ntservice plugin.
This is useful for services that are temporarily stopped but are not critical (e.g., user wants to change the status from critical to warning by `--status-as critical=warning`).
```
> check-ntservice.exe /s PolicyAgent
NtService CRITICAL: PolicyAgent: IPsec Policy Agent - Stopped
> check-ntservice.exe /s PolicyAgent /status-as critcal=warning
NtService WARNING: PolicyAgent: IPsec Policy Agent - Stopped
> check-ntservice.exe /s PolicyAgent /status-as critcal=warning,unknown=warning
NtService WARNING: PolicyAgent: IPsec Policy Agent - Stopped
> check-ntservice.exe /s PolicyAgent /status-as critcal=ok
NtService OK: PolicyAgent: IPsec Policy Agent - Stopped
```
=> introduce status-as option to check-ntservice

check-ping/README.md, check-ping/lib/check-ping.go
implement status-as option to check-ping
```
$ sudo ./build/check-ping --host=10.0.0.0
Ping CRITICAL:
$ sudo ./build/check-ping --host=10.0.0.0 --status-as=CRITICAL=WARNING
Ping WARNING:
```
=> implement status-as option to check-ping
