check-load/README.md, check-load/check_load.go
add loadavg check like [Nagios Plugin](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_load.c)
=> add check-load

check-load/check_load.go, check-load/check_load_darwin.go, check-load/check_load_linux.go
=> Fix check load

check-procs/README.md, check-procs/check_procs.go
This pull request introduces a new check plugin, check-procs. This is a Go port of [Sensu-Plugins-process-checks](https://github.com/sensu-plugins/sensu-plugins-process-checks).
=> add check-procs

Makefile
This pull request adds a new target in Makefile for release.
=> [nit] add release target

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- reduce binary size by using ldflags #15
- Remove cgo dependency from check-load #16
=> Release version 0.0.3

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
=> Release version 0.0.4

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- check-log #21
- Add check-log in the packages #25
=> Release version 0.1.0

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- check-procs for windows #24
- [bug][check-log] fix large file handling #27
=> Release version 0.1.1

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- [check-procs] support `--critical-over=0` and `--warn-over=0` #31
- add check-tcp #32
=> Release version 0.2.0

check-log/check-log.go, check-log/check_log_test.go
- care file rotation properly
- fix logfile handling when the file is not ended with newline character.
=> Fix bugs of check-log

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- Fix bugs of check-log #35
- [check-log] add --no-state option #36
=> Release version 0.2.1

README.md, check-ntpoffset/README.md, check-ntpoffset/check-ntpoffset.go
I'd like to add a plugin to check ntpoffset.
The plugin is from my repository(https://github.com/hiroakis/mackerel-agent-checks-plugins)
I adjusted your coding style referring to other plugins.
If there are anything strange, please let me know.
=> A plugin to check ntpoffset

check-tcp/check-tcp.go, check-tcp/check-tcp_test.go
- add `-U|--unix-sock` option
- add TestUnixDomainSocket
=> Check tcp unix domain socket

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- A plugin to check ntpoffset #38
- Check tcp unix domain socket #39
- [check-tcp] add ipv6 support #42
=> Release version 0.2.2

check-http/check_http.go, check-http/check_http_test.go
this is simple implementation of issue #48 .
=> add --no-check-certificate options to check_http

check-mailq/README.md, check-mailq/check_mailq.go
inspired by [check_mailq.pl](https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-scripts/check_mailq.pl)
Nagios plugin covers several MTA's check by one script, so I started to write like that. also this plugin currently works for only Postfix...
Is it good to separate MTA check into each one script?
=> add check-mailq, currently only available for postfix.

check-postgresql/README.md, check-postgresql/check-postgresql.go, check-postgresql/connection.go
I'll try to implement with test codes and other sub commands later at other pull request.
I'm sorry. Please start to review. @Songmu
=> add check-postgresql

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
=> Release version 0.3.1

check-redis/README.md, check-redis/check-redis.go
=> Add check-redis

check-elasticsearch/README.md, check-elasticsearch/check_elasticsearch.go
=> Add check-elasticsearch

check-mailq/check_mailq.go
qmail-qstat is needed in `$PATH`
=> add qmail queue check to check-mailq

.travis.yml, CHANGELOG.md, README.md, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- Fix duplicated help message #58
- add qmail queue check to check-mailq #59
- Add check-elasticsearch #62
- Add check-redis #63
- check-procs: check PPID #64
=> Release version 0.4.0

check-tcp/check-tcp.go
Some time check-tcp could not retrieve content with EOF error.
net.read returns content with EOF error.
ref. http://dsas.blog.klab.org/archives/cat_50043510.html
=> Fixed slurp. conn.read returns content with EOF

check-cert-file/README.md, check-cert-file/check-cert-file.go
This check plugin is useful for checking expiry of a local certification file.
=> add check-cert-file

check-mysql/README.md, check-mysql/check-mysql.go, check-mysql/uptime.go
check-mysql-uptime is used to detect a unexpected reboot
=> Add uptime sub command to check-mysql

README.md, check-file-size/README.md, check-file-size/check_file_size.go, check-file-size/check_file_size_test.go
The plugin checks the files size of specified directory.
As an use case, to check the Fluentd files buffer directory if the files buffer increases large size.
=> Check file size

check-elasticsearch/README.md, check-elasticsearch/check_elasticsearch.go
Add scheme option to check-elasticsearch.
=> Add scheme option to check-elasticsearch

check-solr/README.md, check-solr/check_solr.go, check-solr/ping.go
I'll try to implement with test codes and other sub commands later at other pull request.
I'm sorry. Please start to review. @Songmu
=> add check-solr

check-memcached/README.md, check-memcached/check-memcached.go
=> check-memcached

packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
use `/usr/bin/check-*`, and put symlinks into `/usr/local/bin/check-*` (old only)
=> use /usr/bin/check-*

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- use /usr/bin/check-* #91
- use GOARCH=amd64 for now #93
=> Release version 0.5.1

packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
Reverts mackerelio/go-check-plugins#91
=> Revert "use /usr/bin/check-*"

.travis.yml, CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- Revert "use /usr/bin/check-*" #95
=> Release version 0.5.2

packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
Reverts mackerelio/go-check-plugins#95
=> Revert "Revert "use /usr/bin/check-*""

check-procs/README.md, check-procs/check_procs.go, check-uptime/README.md, check-uptime/check-uptime.go
=> [uptime/procs] `--warn-over/under` is deprecated. use `--warning-over/under` instead

README.md, check-aws-sqs-queue-size/README.md, check-aws-sqs-queue-size/check-aws-sqs-queue-size.go
I'd like to add the plugin to check SQS queue size.
=> Plugin for checking AWS SQS queue size

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- Fixed argument parser error: #113
=> Release version 0.6.2

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- Add option for skip searching logfile content if logfile does not exist #115
- [check-log] write file atomically when saving read position into state file #119
=> Release version 0.7.0

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
* [check-log] improve Windows support #122 (daiksy)
<details>
<summary>outdated</summary>
- Add check-file-age #1
- add check-load #2
- Refactor/check http #3
- Packaging preparation #6
- for windows #122
</details>
=> Release version 0.8.0

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- Fix state in check-procs #124
- Fix the links to the document #125
- remove checking Ignore #126
- [check-log] fix state file path (fix wrong slice copy) #127
=> Release version 0.8.1

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
* add check-windows-eventlog #129 (daiksy)
* [check-log]fix encoding option #131 (daiksy)
=> Release version 0.9.0

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- [check-log] support glob in --file option #133
=> Release version 0.9.1

check-windows-eventlog/README.md, check-windows-eventlog/check-windows-eventlog.go, check-windows-eventlog/check_windows_eventlog_test.go
This revert `--event-id`. And add `--event-id-pattern` and `--event-id-exclude`
=> Fix exclude

check-windows-eventlog/README.md, check-windows-eventlog/check-windows-eventlog.go, check-windows-eventlog/check_windows_eventlog_test.go
=> add --source-exclude and --message-exclude, --id

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- [check-windows-eventlog] add --source-exclude, --message-exclude and --event-id #136 (mattn, daiksy)
- [check-windows-eventlog] remove --event-id and add --event-id-pattern, --event-id-exclude #137 (mattn)
=> Release version 0.9.2

check-log/check-log.go
pointed out by @haya14busa
https://github.com/mackerelio/mackerel-agent/pull/333/files#r101444496
=> ensure close temporary file in writeFileAtomically

CHANGELOG.md, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- ensure close temporary file in writeFileAtomically #141
- Write the file in same directory #142
=> Release version 0.9.4

check-tcp/check-tcp.go
The `-timeout` option doesn't work when waiting tcp connection, so I fixed.
=> [check-tcp] connect timeout

appveyor.yml
=> run tests under ./check-XXX/lib

.travis.yml, appveyor.yml, check-masterha/lib/check_masterha_test.go
Same as https://github.com/mackerelio/mkr/pull/95
https://travis-ci.org/mackerelio/go-check-plugins/builds/216646003
=> bump go to 1.8

check-ntservice/lib/check_ntservice.go, check-ntservice/lib/check_ntservice_others.go, check-ntservice/lib/check_ntservice_test.go, check-ntservice/lib/check_ntservice_windows.go, check-procs/lib/check_procs_test.go, check-procs/lib/check_procs_windows.go
execute wmic command taks bits heavy CPU/Memory loads.
=> use wmi query instead of running wmic command

check-log/lib/check-log.go, check-windows-eventlog/lib/check-windows-eventlog.go
Implemented at https://github.com/mackerelio/golib/pull/4
=> Use golib/pluginutil.PluginWorkDir()

CHANGELOG.md, Makefile, README.md, mackerel-check.go, packaging/deb/debian/changelog, packaging/deb/debian/rules, packaging/rpm/mackerel-check-plugins.spec
- [experimental] update release scripts #168
=> Release version 0.10.2

check-ssh/lib/check-ssh.go
ref: https://github.com/golang/go/issues/19767
=> [check-ssh] fix the problem that check-ssh cannot invoke SSH connection

CHANGELOG.md, Makefile, mackerel-check.go, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins.spec
- [ntpoffset] support chronyd #166
- [check-ssh] fix the problem that check-ssh cannot invoke SSH connection #171
=> Release version 0.10.3

README.md
- Remove "CentOS 5" / "Debian 6"
- Add links to setup package repositories
=> Refine installation instruction

check-log/README.md
Using globs in mackerel-agent.conf is sometimes difficult……
So I'd like to add some descriptions to README.
=> [check-log] Add description for using globs

check-http/README.md, check-http/lib/check_http.go, check-http/lib/check_http_test.go
Possible patterns:
```
-s 404=ok
-s 300-404=critical
```
Fixes #181
=> Status map

check-http/lib/check_http.go, check-http/lib/check_http_test.go
=> add -i flag to specify source IP

tool/cpanfile
ref: https://github.com/mackerelio/Mackerel-ReleaseUtils/pull/2
=> Update Mackerel::ReleaseUtils to check git workspace is clean

check-mysql/lib/check-mysql.go, check-mysql/lib/readonly.go
check-mysqlでreadonlyの監視機能を追加してみました
=> [check-mysql] add readonly subcommand

check-mysql/lib/check-mysql.go, check-postgresql/lib/check-postgresql.go, check-ssh/lib/check-ssh.go
Update for setting password via environment variable.
- check-ssh
- `LOGIN_PASSWORD`
- check-mysql
- `MYSQL_PASSWORD`
- check-postgresql
- `PGPASSWORD`
=> Setting password via environment variable

check-http/lib/check_http.go
=> Avoid race condition in checkhttp.Run()

check-procs/lib/check_procs_unix.go
=> [check-procs] fix `getProcs` error handling

check-http/lib/check_http.go, check-http/lib/check_http_test.go
* For those who want to use host header option.
* check_http plugin has the same option.
=> [check-http] add host header option

mackerel-check_gen.go, packaging/config.json
With this pull request check-ldap plugin, implemented in #227, is included in the package.
=> add check-ldap to the package

check-mysql/README.md, check-mysql/lib/check-mysql.go
See also.
- https://github.com/mackerelio/mackerel-agent-plugins/blob/master/mackerel-plugin-mysql/lib/mysql.go#L325-L329
- https://github.com/mackerelio/mackerel-agent-plugins/blob/master/mackerel-plugin-mysql/lib/mysql.go#L1030-L1035
=> [check-mysql] add unix socket option

check-windows-eventlog/lib/check-windows-eventlog.go
modified message because many asking about the meaning of error messages
=> modify message check-windows-eventlog

mackerel-check_gen.go, packaging/config.json
=> [nit] add check-smtp to package

README.md, mackerel-check_gen.go, packaging/config.json
https://github.com/mackerelio/go-check-plugins/pull/248
=> add aws-cloudwatch-logs

check-aws-cloudwatch-logs/README.md, check-aws-sqs-queue-size/README.md, check-cert-file/README.md, check-disk/README.md, check-elasticsearch/README.md, check-file-age/README.md, check-file-size/README.md, check-http/README.md, check-jmx-jolokia/README.md, check-ldap/README.md, check-load/README.md, check-log/README.md, check-mailq/README.md, check-masterha/README.md, check-memcached/README.md, check-mysql/README.md, check-ntpoffset/README.md, check-ntservice/README.md, check-postgresql/README.md, check-procs/README.md, check-redis/README.md, check-smtp/README.md, check-solr/README.md, check-ssh/README.md, check-ssl-cert/README.md, check-tcp/README.md, check-uptime/README.md, check-windows-eventlog/README.md
refs https://github.com/mackerelio/go-check-plugins/pull/272
=> Improve READMEs

CHANGELOG.md, packaging/deb-v2/debian/changelog, packaging/deb/debian/changelog, packaging/rpm/mackerel-check-plugins-v2.spec, packaging/rpm/mackerel-check-plugins.spec
We SHOULD list EijiSugiura, the original author of #276.
=> add the original author's name to changelog

check-ldap/lib/check_ldap.go
Current 386 binary throws runtime error on my environment (Debian 8, x86_64).
```
$ /usr/bin/check-ldap -b 'dc=example,dc=com' -w 5 -c 10
2019/04/01 19:13:03 ldap: recovered panic in processMessages: runtime error: invalid memory address or nil pointer dereference
LDAP UNKNOWN: LDAP Result Code 200 "Network Error": ldap: response channel closed
```
https://github.com/go-ldap/ldap/pull/199 should fix this issue and this patch exists only in v3, so I updated go-ldap package.
=> [check-ldap] Update go-ldap to v3

check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs.go
I changed check-aws-cloudwatch-logs to use atomic.WriteFile instead of using syscalls directly.
This p-r followed implementation of *check-log*.
=> make handling a state file more safe

README.md
I added two links to refer repository policy.
=> [doc]add repository policy

check-redis/lib/check-redis.go
=> [check-redis] Add password support for check-redis

Makefile
ref mackerelio/mackerel-agent-plugins#626
=> ignore diffs of go.mod and go.sum

check-postgresql/UPDATE.md, check-postgresql/test.sh
I added basic tests for check-postgresql.
=> [check-postgresql] add test.sh

check-http/README.md, check-http/lib/check_http.go
Hi,
I want to add some other options for the check-http based on https://github.com/sensu-plugins/sensu-plugins-http/blob/master/bin/check-http.rb. Does it seems good ?
=> [check-http]adding more options to check-http

check-log/lib/check-log_test.go
`testCancel` sometimes fails on Windows (ref: https://github.com/mackerelio/go-check-plugins/pull/403#issuecomment-680782111).
I modified this test by removing timestamp comparison to avoid such failures.
=> [check-log] stabilize time-dependent tests

check-disk/lib/check-disk.go, check-disk/lib/check-disk_test.go
Signed-off-by: hurrycaine <jason.e.joyner@gmail.com>
=> Closes #440 added sort the chec-disk output

.github/workflows/test.yml
change to one with appropriate privileges
=> replace token

.github/workflows/test.yml, check-smtp/lib/check-smtp_test.go, go.mod
=> upgrade go1.14 -> 1.16

.github/workflows/create-release-pr.yml
It was missing, so I added it.
=> append actions/checkout

check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_test.go, check-aws-cloudwatch-logs/lib/check-aws-cloudwatch-logs_unix.go
=> [check-aws-cloudwatch-logs] stop gracefully on timeout signal

check-http/test.sh, check-http/testdata/index.html
I added **check-http/test.sh**. It tests:
- access local HTTP service directly
- access local HTTP service via local squid proxy
=> [check-http] add test.sh

.github/workflows/test.yml
refer https://github.com/mackerelio/mackerel-agent/pull/903
=> added build tests.

.github/dependabot.yml, .github/workflows/test.yml
* use mackerelio/workflows
* upgrade Go
=> use mackerelio/workflows and upgrade maximum Go version to 1.21

.github/workflows/test.yml
fix https://github.com/mackerelio/go-check-plugins/actions/runs/6568502499/job/17843105674
=> bump go version on build

check-log/lib/check-log.go
2 similer problems.
1. `os.ReadDir` function may return an error from [lstat](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/os/dir_unix.go;l=132) when the file is removed within the period of running `os.ReadDir` function. If the error occurs, `os.ReadDir` function returns entries it was able to read before the error https://pkg.go.dev/os@go1.22.0#ReadDir .
2. `DirEntry.Info` method may return an error when the file is removed between the process runs `os.ReadDir` function and runs `DirEntry.Info` method. The error satisfies `errors.Is(err, ErrNotExist)` accroding to https://pkg.go.dev/io/fs@go1.22.0#DirEntry .
=> Reduce check-log errors when a file in the log directory has been removed at the moment of running check-log

check-mailq/lib/check_mailq.go
This patch is ported from https://github.com/mackerelio/mackerel-agent-plugins/pull/1186
=> [check-mailq] fix pattern

.github/workflows/create-release-pr.yml, .github/workflows/test.yml, check-windows-eventlog/lib/check-windows-eventlog.go, check-windows-eventlog/lib/check_windows_eventlog_test.go
Added Information  to the monitoring targets.
=> [check-windows-eventlog] add target event type

check-windows-eventlog/lib/check-windows-eventlog.go
=> [check-windows-eventlog] add status-as option

CHANGELOG.md, packaging/deb-v2/debian/changelog, packaging/rpm/mackerel-check-plugins-v2.spec
Reverts mackerelio/go-check-plugins#917
=> Revert "Release version 0.49.0"

.github/dependabot.yml, .github/workflows/create-release-pr.yml, .github/workflows/test.yml
I did.
also added grouping aws-sdk-go-v2/*
=> added dependabot cooldown
